### ISSUE TITLE
run the osIntercom in WhiteCoreSim ?

### ISSUE THREAD

**Issue by BogusCurry** [djphil/osintercom#1]
hi ;)
Run this Script in WhiteCoreSim or only in OpenSim ?

Greetings

Bogus

**Comment by djphil** [comment]
Hello! ;)

You can on Aurora-Sim, WhiteCoreSim, Moses, Halcyon, OpenSim and Second Life.

Enjoy!

**Comment by BogusCurry** [comment]
nice ;D
And the another Script from you too ?

**Comment by BogusCurry** [comment]
And how I can use this ?

**Comment by djphil** [comment]
Some of the other scripts might work with Aurora-Sim but others will not work because either the name of the database is different (or table) or the service used is different. However it should be easy enough for the adapater Aurora-Sim (or WhiteCoreSim).

To use, you can get help by clicking on the small link "help" just below the Intecom web page.
